name: Package Import Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  import-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    
    - name: Install dependencies
      run: |
        conda install -y -c conda-forge \
          numpy>=1.26 \
          pandas \
          geopandas \
          rasterio \
          xarray \
          netCDF4 \
          cdsapi \
          scikit-learn \
          shapely \
          matplotlib \
          wheel \
          setuptools \
          pyproj \
          zarr \
          cftime \
          h5netcdf
        
        # Install the package in development mode
        pip install . --no-deps --ignore-installed -vv